### ISSUE TITLE
Installation instructions on MacOS High Sierra and Mojave

### ISSUE THREAD

**Issue by asgeir386** [microsoft/ivy#38]
Hi,

The installation instructions we've come up with at Apple for MacOS are the following, and because there are some extra steps required we thought this might be helpful for people getting started with IVy on MacOS

Please add to IVy installation documentation if you agree this might be helpful

Follow up questions can be directed to aeiriksson at apple.com

Regards,

'Asgeir

Installation instructions on MacOS High Sierra and Mojave

Preliminaries:
1. Install Xcode from App Store
2. Install Xcode command line tools
   > xcode-select --install 
 3.  Install Xserver 
   - https://www.xquartz.org 
 4. Macports
> sudo xcodebuild -license 
https://www.macports.org/install.php (select matching macOS 10.12 or 10.13 depending on macOS running on machine)
macOS 10.3 Mojave (make sure you've installed all patches because various steps below were broken until about 7/15/2019 patch)
> sudo easy_install pip (required on 10.13 Mojave and/or required by 8/1/2019)
a) sudo port install graphviz-gui
 sudo port select --set python python27
 sudo port select --set python2 python27
sudo pip install pygraphviz --install-option="--include-path=/opt/local/include" --install-option="--library-path=/opt/local/lib"
  b) sudo port install Tix
  c) sudo port install py27-ply
  d) sudo port install py27-ipython
  e) suo port install py27-tkinter (added this step with 10.13 Mojave)
5. Install Z3
- https://github.com/Z3Prover/z3
  Select download zip in the “Clone or download” button
$ pwd
/Users/asgeireiriksson/Downloads/z3-master
> python scripts/mk_make.py
> cd build
> make
> sudo make install 
> sudo pip install z3-solver
 
6. Install Ivy:
https://github.com/Microsoft/ivy
-Select download zip in the “Clone or download” button
 
$ pwd
/Users/asgeireiriksson/Downloads/ivy-master
$ sudo python setup.py install 
export PATH=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin:$PATH
 
7 running test
> pwd 
/Users/asgeireiriksson/Downloads/ivy-master
> cd doc/examples
> ivy_check diagnose=true client_server_example.ivy

**Comment by kenmcmil** [comment]
Thanks Asgeir. Question -- you are recommending to use the master branch of Z3. In my experience that has not worked due to some breaking changes in the Z3 API, so I have been recommending to use release 4.6.0. Has the master branch worked for you?

**Comment by asgeir386** [comment]
Hi Ken,

The version I picked up is 4.8.5 and I ran a full regression with the
expected results and improved run-time compared to 4.5.* which is the
version I used before

I would go with the z3 version that you recommend

The Ivy part has been working well for me me too, i.e. it detected some
logic fragment violations compared to the previous version (about 1 year
old) and fixed some issues I was seeing in the counter-examples

I'm not always sure what version of z3 I'm using with Ivy (the one picked
up by the python binding) and I don't think ivy has a command argument that
would report the z3 version ivy is using

'Asgeir

**Comment by kenmcmil** [comment]
OK, I will recommend Z3 4.6 for now.

Yes, the version is the one that python sees. To get the version:

```
$ python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import z3
>>> z3.get_version()
(4L, 4L, 2L, 0L)
>>> 
``` 

So the means I'm using version 4.4, build 2, rev 0.

**Comment by kenmcmil** [comment]
Done.
