### ISSUE TITLE
Installation instructions on MacOS: correct z3 part

### ISSUE THREAD

**Issue by asgeir386** [microsoft/ivy#39]
When I downgraded z3 back to 4.6.0 from 4.8.5 I needed to change the Ivy installation process in the following way. Once I installed z3 4.6.0 successfully ivy_to_cpp works again (it was running into the API changes you mentioned before).

Please update MacOS installation instructions for the z3 part

5. Install Z3
5.1 Use pip install z3-solver when that works
> sudo pip install z3-solver (will install the newest version)
> sudo pip install z3-solver==4.5.1.0.post2 (will install that version)

5.2 Build the executable locally (when pip doesn't have the required version e.g. 4.6.0 when checked on 09/03/2019)
Download the following file 
https://github.com/Z3Prover/z3/archive/z3-4.6.0.tar.gz
> cd ~/Downloads/z3-z3-4.6.0
> python scripts/mk_make.py --prefix=/opt/local/Library/Frameworks/Python.framework/Versions/2.7 --python --pypkgdir=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
> cd build
> make -j 4
> sudo make install 

---
To check version accessed by Ivy after 5.1 or 5.2 above
> python
> import z3
> z3.get_version()
(4L, 6L, 0L, 0L)
indicates 4.6.0

**Comment by kenmcmil** [comment]
OK, I changed the directions for z3-4.6.0, but did not include the older versions, since I would prefer not to support those.
