### ISSUE TITLE
compilation of quantifier over iterable

### ISSUE THREAD

**Issue by nano-o** [microsoft/ivy#56]
Hello, I am trying to generate code using module `simple_tcp`, as follows:
```
#lang ivy1.7
include tcp
instance node : iterable
type t
interpret t -> int
instance net : simple_tcp(node, t)
export net.send
import net.recv
extract code(self:node) = net(self), node
```
Why I run `ivyc isolate=code target=class tcp_test.ivy` I get the following error:
`ivy/include/1.7/tcp.ivy: line 243: error: cannot find an upper bound for loc:other`
This corresponds to an existential quantification over sort node.

It seems that `attribute cardinality = size` in `iterable` should enable code generation for quantification over node, or I am doing something wrong?

**Comment by kenmcmil** [comment]
I can't repro that issue. Can you try it on latest master?

**Comment by nano-o** [comment]
Indeed it works on the latest master with ivyc. However with ivy_to_cpp the error appears (looks like I got confused between those two commands). Is ivy_to_cpp now deprecated?

**Comment by nano-o** [comment]
I forgot to specify `isolate=code` on the command line, and with that ivy_to_cpp works too. Sorry for the noise.

**Comment by kenmcmil** [comment]
I'm maintaining `ivy_to_cpp` for backward compatibility with scripts. It interprets the command line parameters a little differently than `ivyc`. With `ivyc` the defaults are `target=repl build=true`. Also, if your program has one extract, then this is default isolate for `target=repl` and `target=class`.   This cuts down on the length of the comma line. In the normal case, you just need `ivyc target=class file.ivy`.
