### ISSUE TITLE
Soundness issue with `before` and `after`?

### ISSUE THREAD

**Issue by nano-o** [microsoft/ivy#73]
Hello, `ivy_check` does not complain when verifying the following file. Is this a bug or am I misunderstanding what `before` and `after` mean? (the same thing happen using `after`)
```
#lang ivy1.7

isolate iso_1 = {
    action my_action = {
        require false
    }
}

isolate iso_2 = {
    export action my_action = {
    }
    before my_action {
        call iso_1.my_action
    }
} with iso_1

```

**Comment by kenmcmil** [comment]
Fixed in commit f2b10af. Thanks!
