### ISSUE TITLE
_generating detected as unknown symbol

### ISSUE THREAD

**Issue by prpr2770** [microsoft/ivy#76]
Using ivy_check and ivy_to_cpp for testing the quic-scripts generates the following error. 

```
(base) # ivy_to_cpp ./quic_connection.ivy 
quic_frame.ivy: line 486: error: unknown symbol: _generating
```

**Comment by kenmcmil** [comment]
This behavior is intended. The symbol _generating only makes sense when you are building a tester with `target=test`.
