### ISSUE TITLE
Associativity of implication changed from right to left in v1.7

### ISSUE THREAD

**Issue by jtassarotti** [microsoft/ivy#91]
When running `ivy_check` on the following code snippet, the conjecture fails:

```
#lang ivy1.7

relation p
relation q

conjecture (p -> q -> p & q)
```

but the same snippet with ivy1.6 succeeds:

```
#lang ivy1.6

relation p
relation q

conjecture (p -> q -> p & q)
```
If this change was deliberate it seems substantial enough to be worth mentioning on https://microsoft.github.io/ivy/language.html as a change from 1.6 to 1.7. 

Apologies if this has already changed on the master branch. I'm not sure which version of ivy_check I am running. I had trouble building from source, so I used the pip installer a few weeks ago. (Is there a way to get ivy to tell me the version?)

**Comment by kenmcmil** [comment]
Ouch. I can see where that bug got in. Unfortunately, fixing it at this point might break a lot of Ivy programs. The best I can do is make a note of the error in the docs and fix it in version 2.0.

Thanks for pointing it out!

**Comment by jtassarotti** [comment]
Yes, I can see how changing it back again might break other programs that have come to rely on the left associativity. One other possibility might be to add an option to check whether a file uses `->` in an ambiguous way and issue a warning. Not sure how annoying that would be to implement with the current parsing strategy, but it could be especially helpful for porting developments from 1.6 to 1.7 and from 1.7 to 2.0+ in the future. I personally had an axiom that was sound under the 1.6 parsing and implied false under 1.7, and only realized after I was skeptical about why `ivy_check` was suddenly running so fast after switching to 1.7.

**Comment by kenmcmil** [comment]
Good point. It would be easy to give a warning.

**Comment by kenmcmil** [comment]
Warning added in commit ba00349. Thanks!
